// These constants represent the RISC-V ELF and the image ID generated by risc0-build.
// The ELF is used for proving and the ID is used for verification.
use methods::{
    GUEST_CODE_FOR_ZK_PROOF_ELF, GUEST_CODE_FOR_ZK_PROOF_ID
};
use risc0_zkvm::{default_prover, ExecutorEnv};
use curve25519_dalek::edwards::{EdwardsPoint, CompressedEdwardsY};
use curve25519_dalek::constants::ED25519_BASEPOINT_POINT;

fn main() {
    // Initialize tracing. In order to view logs, run `RUST_LOG=info cargo run`
    tracing_subscriber::fmt()
        .with_env_filter(tracing_subscriber::filter::EnvFilter::from_default_env())
        .init();

    // Create two points - using the basepoint and its double as an example
    let point1 = ED25519_BASEPOINT_POINT;
    let point2 = ED25519_BASEPOINT_POINT + ED25519_BASEPOINT_POINT;

    // Create the executor environment with our input points
    let env = ExecutorEnv::builder()
        .write(&point1.compress().to_bytes())
        .unwrap()
        .write(&point2.compress().to_bytes())
        .unwrap()
        .build()
        .unwrap();

    // Obtain the default prover.
    let prover = default_prover();

    // Prove the execution
    let prove_info = prover
        .prove(env, GUEST_CODE_FOR_ZK_PROOF_ELF)
        .unwrap();

    // Extract the receipt
    let receipt = prove_info.receipt;

    // Get the result from the journal
    let result_bytes: [u8; 32] = receipt.journal.decode().unwrap();
    let result = CompressedEdwardsY(result_bytes)
        .decompress()
        .expect("Invalid result point");

    println!("Result point: {:?}", result);

    // Verify the receipt
    receipt
        .verify(GUEST_CODE_FOR_ZK_PROOF_ID)
        .unwrap();
}
